### ISSUE TITLE
example fails with "illegal seek" error

### ISSUE THREAD

**Issue by larsks** [zacharydenton/wavebender#5]
Trying to run the demo:

```
$ python examples/binaural.py | aplay
```

Results in the following traceback:

```
Traceback (most recent call last):
  File "examples/binaural.py", line 8, in <module>
    write_wavefile(stdout, samples)
  File "/home/lars/src/wavebender/wavebender/__init__.py", line 98, in write_wavefile
    w.writeframesraw(frames)
  File "/usr/lib64/python2.7/wave.py", line 422, in writeframesraw
    self._ensure_header_written(len(data))
  File "/usr/lib64/python2.7/wave.py", line 473, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/lib64/python2.7/wave.py", line 481, in _write_header
    self._form_length_pos = self._file.tell()
IOError: [Errno 29] Illegal seek
Exception IOError: (29, 'Illegal seek') in <bound method Wave_write.__del__ of <wave.Wave_write instance at 0x7f91cacd7320>> ignored
aplay: playback:2715: read error
```

It looks as if the code is trying to call `seek` on `stdout`.  An `strace` confirms:

```
lseek(1, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
```

**Comment by larsks** [comment]
Hmm, this may just be an intrinsic problem with the Python `wave` module, which looks as if it assumes seekable output.  Did those examples ever work?  This is Python 2.7.

**Comment by JesseAldridge** [comment]
only seems to work with python3

**Comment by chrisspen** [comment]
I also get this error. A note that this package is Python>=3 only would be nice...

**Comment by chrisspen** [comment]
I get this error with both Python2.7 and Python3.

    $ virtualenv --python=python3 .env
    $ . .env/bin/activate
    $ pip install -e git://github.com/zacharydenton/wavebender.git#egg=wavebender
    $ python3 binaural.py | aplay
    Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
    Traceback (most recent call last):
      File "binaural.py", line 14, in <module>
        write_wavefile(stdout, samples)
      File "/myproject/.env/src/wavebender/wavebender/__init__.py", line 98, in write_wavefile
        w.writeframesraw(frames)
      File "/usr/lib/python3.4/wave.py", line 421, in writeframesraw
        self._file.write(data)
    BrokenPipeError: [Errno 32] Broken pipe
    Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write object at 0x7fd4e78ef710>>
    Traceback (most recent call last):
      File "/usr/lib/python3.4/wave.py", line 315, in __del__
        self.close()
      File "/usr/lib/python3.4/wave.py", line 435, in close
        self._patchheader()
      File "/usr/lib/python3.4/wave.py", line 482, in _patchheader
        curpos = self._file.tell()
    OSError: [Errno 29] Illegal seek

**Comment by feinstaub** [comment]
Hi, I get the same error with python3 on openSUSE 42.1. I here a very short sound and then the error message appears. This is what I executed: python3 binaural.py | aplay

**Comment by theSage21** [comment]
python 3.5.2, Archliunx, aplay 1.1.2

**Comment by feinstaub** [comment]
Problem still persists with openSUSE 42.1, Python 3.4.5, aplay: version 1.1.2 (from multimedia:libs)

**Comment by alfstorm** [comment]
This works for me when I rewind back to [89d8d65](https://github.com/zacharydenton/wavebender/commit/89d8d653606ca5016e1eccc38e3a6c68eb8fd32b) with Ubuntu 16.04 and python 2.7.12.

**Comment by wastevensv** [comment]
@feinstaub What is the text of the error? On Ubuntu, with Python 3.4.5, and aplay 1.1.0, I get the following:
```
Tue Nov 22 02:11:40 [wasv@wasv-HP-Envy] wavebender 
9512$ python -m wavebender - | aplay
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
^CAborted by signal Interrupt...
aplay: pcm_write:1940: Traceback (most recent call last):
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/runpy.py", line 170, in _run_module_as_main
write error: Interrupted system call
    "__main__", mod_spec)
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wasv/Documents/wavebender/wavebender/__main__.py", line 3, in <module>
    main()
  File "/home/wasv/Documents/wavebender/wavebender/__init__.py", line 135, in main
    write_wavefile(filename, samples, args.rate * args.time, args.channels, args.bits // 8, args.rate)
  File "/home/wasv/Documents/wavebender/wavebender/__init__.py", line 98, in write_wavefile
    w.writeframesraw(frames)
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/wave.py", line 422, in writeframesraw
    self._file.write(data)
KeyboardInterrupt
Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write object at 0x7f1d8c426780>>
Traceback (most recent call last):
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/wave.py", line 316, in __del__
    self.close()
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/wave.py", line 436, in close
    self._patchheader()
  File "/home/wasv/.pyenv/versions/3.4.5/lib/python3.4/wave.py", line 484, in _patchheader
    curpos = self._file.tell()
OSError: [Errno 29] Illegal seek
Tue Nov 22 02:11:52 [wasv@wasv-HP-Envy] wavebender 
9513$ python --version
Python 3.4.5
Tue Nov 22 02:11:57 [wasv@wasv-HP-Envy] wavebender 
9514$ aplay --version
aplay: version 1.1.0 by Jaroslav Kysela <perex@perex.cz>
Tue Nov 22 02:14:19 [wasv@wasv-HP-Envy] wavebender 
9515$ 
```
The exception does still occur, but it is caught and ignored, and aplay played the audio correctly.

However, I do notice that python 3.4.5 uses it's built in wave.py, rather than the patched one in this repository. I will be submitting a fix for that soon. Please let me know if that fixes it.

**Comment by feinstaub** [comment]
```python3 square.py | aplay```
works.

```python3 -m wavebender - | aplay```
works.

```python3 -m wavebender -t 1 -f 5000  - | aplay```
works.

But this still fails:

```
~/dev/src/wavebender/examples[master *]> python3 binaural.py | aplay
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                          
  File "binaural.py", line 8, in <module>                                                                                                                                                                                                   
    write_wavefile(stdout, samples)                                                                                                                                                                                                         
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/__init__.py", line 98, in write_wavefile                                                                                                                                 
    w.writeframesraw(frames)                                                                                                                                                                                                                
  File "/usr/lib64/python3.4/wave.py", line 422, in writeframesraw                                                                                                                                                                          
    self._file.write(data)                                                                                                                                                                                                                  
BrokenPipeError: [Errno 32] Broken pipe                                                                                                                                                                                                     
Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write object at 0x7fd94abb8208>>                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                          
  File "/usr/lib64/python3.4/wave.py", line 316, in __del__                                                                                                                                                                                 
    self.close()                                                                                                                                                                                                                            
  File "/usr/lib64/python3.4/wave.py", line 436, in close                                                                                                                                                                                   
    self._patchheader()
  File "/usr/lib64/python3.4/wave.py", line 484, in _patchheader
    curpos = self._file.tell()
OSError: [Errno 29] Illegal seek
```

**Comment by feinstaub** [comment]
Sorry, the last error message is different (I forgot to install with `python3 setup.py install --user`):

```~/dev/src/wavebender/examples[master *]> python3 binaural.py | aplay
Traceback (most recent call last):
  File "binaural.py", line 8, in <module>
    write_wavefile(stdout, samples)
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/__init__.py", line 98, in write_wavefile
    w.writeframesraw(frames)
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 424, in writeframesraw
    self._ensure_header_written(len(data))
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 484, in _write_header
    self._sampwidth * 8, b'data'))
struct.error: required argument is not an integer
Exception ignored in: <bound method Wave_write.__del__ of <wavebender.wave.Wave_write object at 0x7f993f06f208>>
Traceback (most recent call last):
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 332, in __del__
    self.close()
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 446, in close
    self._ensure_header_written(0)
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "/home/gregor/.local/lib/python3.4/site-packages/wavebender/wave.py", line 484, in _write_header
    self._sampwidth * 8, b'data'))
struct.error: required argument is not an integer
aplay: playback:2716: read error
```

**Comment by feinstaub** [comment]
This is a quick & dirty fix which makes the binaural.py work for me (plays the tone for 1 second):

```
#!/usr/bin/env python
from wavebender import *

channels = ((sine_wave(170.0, amplitude=0.5),),
            (sine_wave(278.0, amplitude=0.5),))

samples = compute_samples(channels, 44100)
write_wavefile(stdout, samples, 44100, 2, 16 // 8, 44100)
```
